# Generated by Django 4.1.7 on 2023-03-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(max_length=100)),
                (
                    "app_name",
                    models.CharField(default="New Application", max_length=50),
                ),
                ("app_secret", models.CharField(max_length=100)),
                ("redirection_url", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
