# Generated by Django 4.1.7 on 2023-02-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('biometric_option', models.CharField(max_length=30)),
                ('fido_option', models.CharField(max_length=30)),
                ('blockchain_auth', models.CharField(max_length=30)),
            ],
        ),
    ]
