# Generated by Django 4.1.7 on 2023-03-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="recovery_email",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="recovery_phone_number",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
