# Generated by Django 4.1.7 on 2023-03-23 14:09

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_recovery_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="public_key",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="face_image",
            field=models.FileField(default="", upload_to=app.models.img_dir_path),
        ),
    ]
