# Generated by Django 4.1.7 on 2023-03-01 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_applications_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("face_auth", models.BooleanField(default=False)),
                ("fido_auth", models.BooleanField(default=False)),
                ("blockchain_auth", models.BooleanField(default=False)),
                ("voice_auth", models.BooleanField(default=False)),
                ("face_image", models.ImageField(default="", upload_to="images/")),
                ("recovery_email", models.CharField(max_length=100)),
                ("recovery_phone_number", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 3, 1, 13, 24, 54, 338735, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="applications",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 1, 13, 24, 54, 337736, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
