# Generated by Django 4.1.7 on 2023-03-01 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_user_alter_applications_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 1, 14, 16, 40, 173869, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 1, 14, 16, 40, 173869, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="recovery_email",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="recovery_phone_number",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
