# Generated by Django 4.1.7 on 2023-04-01 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_user_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecoveryToken",
            fields=[
                (
                    "token",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=100)),
                ("valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(
                default="99c9cc2eff1dc1c25088db73c47690aa", max_length=100, null=True
            ),
        ),
    ]
