# Generated by Django 4.1.7 on 2023-03-01 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_applications_created_at_alter_user_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 1, 14, 17, 31, 612247, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 1, 14, 17, 31, 613247, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
