# Generated by Django 4.1.7 on 2023-04-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_user_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="fido_auth",
            new_name="inapp_auth",
        ),
        migrations.AddField(
            model_name="user",
            name="inapp_public_key",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
