# Generated by Django 4.1.7 on 2023-03-01 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_applications_created_at_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
