# Generated by Django 4.1.7 on 2023-03-01 15:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_applications_created_at_alter_user_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="voice_image",
            field=models.ImageField(default="", upload_to=app.models.audio_dir_path),
        ),
        migrations.AlterField(
            model_name="user",
            name="face_image",
            field=models.ImageField(default="", upload_to=app.models.img_dir_path),
        ),
    ]
