# Generated by Django 4.1.7 on 2023-03-01 15:28

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_user_voice_image_alter_user_face_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="face_image",
            field=models.FileField(default="", upload_to=app.models.img_dir_path),
        ),
    ]
