# Generated by Django 4.1.7 on 2023-04-12 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_testbytes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.BinaryField(
                        blank=True, editable=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "public_key",
                    models.BinaryField(blank=True, editable=True, null=True),
                ),
                ("sign_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name="TestBytes",
        ),
        migrations.AddField(
            model_name="user",
            name="fido_auth",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="credentials",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.user"
            ),
        ),
    ]
