# Generated by Django 4.1.7 on 2023-03-17 16:23

import app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applications",
            fields=[
                (
                    "app_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "app_name",
                    models.CharField(default="New Application", max_length=50),
                ),
                ("app_secret", models.CharField(max_length=100)),
                ("redirection_url", models.CharField(default="", max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("face_auth", models.BooleanField(default=False)),
                ("fido_auth", models.BooleanField(default=False)),
                ("blockchain_auth", models.BooleanField(default=False)),
                ("voice_auth", models.BooleanField(default=False)),
                (
                    "face_image",
                    models.ImageField(default="", upload_to=app.models.img_dir_path),
                ),
                (
                    "voice_image",
                    models.FileField(default="", upload_to=app.models.audio_dir_path),
                ),
                ("recovery_email", models.CharField(default=None, max_length=100)),
                (
                    "recovery_phone_number",
                    models.CharField(default=None, max_length=100),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
