# Generated by Django 4.1.7 on 2023-03-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_applications_public_key_user_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(
                default="483d07268a03422c99d55b352a184ae0", max_length=100, null=True
            ),
        ),
    ]
