# Generated by Django 4.1.7 on 2023-03-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='c455d9333424ec2ab9b7ade8278b4970', max_length=100, null=True),
        ),
    ]
