# Generated by Django 4.1.7 on 2023-04-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rename_fido_auth_user_inapp_auth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="inapp_public_key",
            field=models.BinaryField(default=None, null=True),
        ),
    ]
